stages:
  - build
  - deploy

before_script: 
  - "cd build/source"
  - "chmod 644 private.key"
 
### ---------------- job for master & vp8_test branch ------------------ ### 
## -------> build
build_master_android:
    stage: build
    script: "python build_android.py"
    only:
      - master
      - vp8_test
    tags:
      - mac_mini_178_218

build_master_ios:
    stage: build
    script: "python build_ios.py"
    only:
      - master
      - vp8_test   
    tags:
      - mac_mini_178_218

build_master_win:
    stage: build
    script: "python build_win.py"
    only:
      - master
      - vp8_test
    tags:
      - win_pc


## -----------> deploy
deploy_master_android:
    stage: deploy
    script: "cp ../android_*.zip ~/.ecmedia_libs_archives/all_libs/android/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - mac_mini_178_218

deploy_master_ios:
    stage: deploy
    script: "cp ../ios_*.zip ~/.ecmedia_libs_archives/all_libs/ios/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - mac_mini_178_218

deploy_master_win:
    stage: deploy
    script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.ecmedia_libs_archives/all_libs/windows/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - win_pc


### ---------------- job for branch except master ------------------ ### \

## ------> build
build_br_dev_android:
    stage: build
    script: "python build_android.py"
    only:
      - develop
    tags:
      - mac_mini_178_218

build_br_dev_ios:
    stage: build
    script: "python build_ios.py"
    only:
      - develop
    tags:
      - mac_mini_178_218


build_br_dev_win:
    stage: build
    script: "python build_win.py"
    only:
      - develop
    tags:
      - win_pc


## -------> deploy
deploy_br_other_android:
    stage: deploy
    script: "cp ../android_*.zip ~/.ecmedia_libs_archives/all_libs/android/v2.1.x/"
    only:
      - vp8_test
    tags:
      - mac_mini_178_218
    when: manual
    variables:
      GIT_STRATEGY: none
    

deploy_br_other_ios:
    stage: deploy
    script: "cp ../ios_*.zip ~/.ecmedia_libs_archives/all_libs/ios/v2.1.x/"
    only:
      - vp8_test
    tags:
      - mac_mini_178_218
    when: manual
    variables:
      GIT_STRATEGY: none
    

deploy_br_other_win:
    stage: deploy
    script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.ecmedia_libs_archives/all_libs/windows/v2.1.x/"
    only:
      - vp8_test
    tags:
      - win_pc
    when: manual
    variables:
      GIT_STRATEGY: none
