stages:
  - build
  - test
  - deploy

before_script: 
  - "cd build/source"
  - "chmod 600 ../id_rsa.jenkins"
 
### ---------------- job for master branch ------------------ ### 
## -------> build
build_master_android:
    stage: build
    script: "python build_android.py"
    only:
      - master
    tags:
      - mac_mini_178_218

build_master_ios:
    stage: build
    script: "python build_ios.py"
    only:
      - master
    tags:
      - mac_mini_178_218
    artifacts:
      expire_in: 1 week
      paths:
        - build/*.zip

build_master_win:
    stage: build
    script: "python build_win.py"
    only:
      - master
    tags:
      - win_pc
    artifacts:
      expire_in: 1 week
      paths:
        - build/*.zip


## --------> test
test_master_android:
    stage: test
    script: "echo 'test android ok'"
    only:
      - master
    tags:
      - mac_mini_178_218

test_master_ios:
    stage: test
    script: "echo 'test ios ok'"
    only:
      - master
    tags:
      - mac_mini_178_218

test_master_win:
    stage: test
    script: "echo 'test windows ok'"
    only:
      - master
    tags:
      - win_pc


## -----------> deploy
deploy_master_android:
    stage: deploy
    script: "scp build/android_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/android/v2.3.x/"
    only:
      - master
    tags:
      - mac_mini_178_218

deploy_master_ios:
    stage: deploy
    script: "scp build/ios_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/ios/v2.3.x/"
    only:
      - master
    tags:
      - mac_mini_178_218

deploy_master_win:
    stage: deploy
    script: "scp build/windows_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/windows/v2.3.x/"
    only:
      - master
    tags:
      - win_pc


### ---------------- job for branch except master ------------------ ### \

## ------> build
build_br_dev_android:
    stage: build
    script: "python build_android.py"
    only:
      - develop
      - vp8_test
    tags:
      - mac_mini_178_218
    allow_failure: true
    artifacts:
      expire_in: 1 week
      paths:
        - build/*.zip

build_br_dev_ios:
    stage: build
    script: "python build_ios.py"
    only:
      - develop
      - vp8_test
    tags:
      - mac_mini_178_218
    allow_failure: true


build_br_dev_win:
    stage: build
    script: "python build_win.py"
    only:
      - develop
      - vp8_test
    tags:
      - win_pc
    allow_failure: true
    artifacts:
      expire_in: 1 week
      paths:
        - build/*.zip


## -------> deploy
deploy_br_dev_android:
    stage: deploy
    script: "echo 'deploy android ok'"
    only:
      - vp8_test
    tags:
      - mac_mini_178_218
    when: manual
    script: "scp build/android_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/android/v2.1.x/"

deploy_br_dev_ios:
    stage: deploy
    script: "echo 'deploy ios ok'"
    only:
      - vp8_test
    tags:
      - mac_mini_178_218
    when: manual
    script: "scp build/ios_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/ios/v2.1.x/"

deploy_br_dev_win:
    stage: deploy
    script: "echo 'deploy windows ok'"
    only:
      - vp8_test
    tags:
      - win_pc
    when: manual
    script: "scp build/windows_*.zip jenkins@192.168.179.129:/app/userhome/jenkins/release/ecmedia/windows/v2.1.x/"


