stages:
  - build
  - deploy

before_script: 
  - "cd build/source"
  - "chmod 644 private.key"

## -------> build
build_master_android:
    stage: build
    script: "python build_android.py"
    allow_failure: true
    only:
      - master
      - vp8_test
    tags:
      - mac_osx

build_master_ios:
    stage: build
    script: "python build_ios.py"
    allow_failure: true
    only:
      - master
      - vp8_test   
    tags:
      - mac_osx

build_master_win:
    stage: build
    script: "python build_win.py"
    allow_failure: true
    only:
      - master
      - vp8_test
    tags:
      - windows


## -----------> deploy
deploy_master_android:
    stage: deploy
    script: "cp ../android_*.zip ~/.platform_libs_archives/ecmedia_layer_libs/android/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - mac_osx
    allow_failure: true

deploy_master_ios:
    stage: deploy
    script: "cp ../ios_*.zip ~/.platform_libs_archives/ecmedia_layer_libs/ios/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - mac_osx
    allow_failure: true

deploy_master_win:
    stage: deploy
    script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.platform_libs_archives/ecmedia_layer_libs/windows/v2.3.x/"
    only:
      - master
    variables:
      GIT_STRATEGY: none
    tags:
      - windows
    allow_failure: true


### ---------------- job for branch except master ------------------ ### \

## ------> build
build_br_dev_android:
    stage: build
    script: "python build_android.py"
    only:
      - develop
    tags:
      - mac_osx

build_br_dev_ios:
    stage: build
    script: "python build_ios.py"
    only:
      - develop
    tags:
      - mac_osx


build_br_dev_win:
    stage: build
    script: "python build_win.py"
    only:
      - develop
    tags:
      - windows


## -------> deploy
deploy_br_other_android:
    stage: deploy
    script: "cp ../android_*.zip ~/.platform_libs_archives/ecmedia_layer_libs/android/v2.1.x/"
    only:
      - vp8_test
    tags:
      - mac_osx
    when: manual
    variables:
      GIT_STRATEGY: none
    

deploy_br_other_ios:
    stage: deploy
    script: "cp ../ios_*.zip ~/.platform_libs_archives/ecmedia_layer_libs/ios/v2.1.x/"
    only:
      - vp8_test
    tags:
      - mac_osx
    when: manual
    variables:
      GIT_STRATEGY: none
    

deploy_br_other_win:
    stage: deploy
    script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.platform_libs_archives/ecmedia_layer_libs/windows/v2.1.x/"
    only:
      - vp8_test
    tags:
      - windows
    when: manual
    variables:
      GIT_STRATEGY: none
