stages:
  - build
  - deploy

before_script: 
  - "cd build/source"
  - "chmod 644 private.key"

## -------> build
build_master_android:
    stage: build
    script: "python build_android.py"
    allow_failure: true
    only:
      - master@platform_sdk/ecmedia
    tags:
      - mac_osx

build_master_ios:
    stage: build
    script: "python build_ios.py"
    allow_failure: true
    artifacts:
      name: build_ios.log
      expire_in: 1 week
    only:
      - master@platform_sdk/ecmedia 
    tags:
      - mac_osx

build_master_win:
    stage: build
    allow_failure: true
    script: "python build_win.py"
    only:
      - master@platform_sdk/ecmedia
    tags:
      - windows


# ## -----------> deploy
# deploy_master_android:
#     stage: deploy
#     allow_failure: true
#     script: "cp ../android_*.zip ~/.platform_build/platform_sdk/ecmedia_layer_libs/android/v2.3.x/"
#     script: "cp ../obj_*.zip  ~/.platform_build/platform_sdk/ecmedia_layer_libs/android_obj"
#     only:
#       - master@platform_sdk/ecmedia
#     variables:
#       GIT_STRATEGY: none
#     tags:
#       - mac_osx
#     allow_failure: true

# deploy_master_ios:
#     stage: deploy
#     allow_failure: true
#     script: "cp ../ios_*.zip ~/.platform_build/platform_sdk/ecmedia_layer_libs/ios/v2.3.x/"
#     only:
#       - master@platform_sdk/ecmedia
#     variables:
#       GIT_STRATEGY: none
#     tags:
#       - mac_osx
#     allow_failure: true

# deploy_master_win:
#     stage: deploy
#     allow_failure: true
#     script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.platform_build/platform_sdk/ecmedia_layer_libs/windows/v2.3.x/"
#     only:
#       - master@platform_sdk/ecmedia
#     variables:
#       GIT_STRATEGY: none
#     tags:
#       - windows
#     allow_failure: true


### ---------------- job for branch except master ------------------ ### \

## ------> build
build_br_dev_android:
    stage: build
    allow_failure: true
    when: manual
    script: "python build_android.py"
    only:
      - develop@platform_sdk/ecmedia
    tags:
      - mac_osx

build_br_dev_ios:
    stage: build
    allow_failure: true
    when: manual
    script: "python build_ios.py"
    only:
      - develop@platform_sdk/ecmedia
    tags:
      - mac_osx


build_br_dev_win:
    stage: build
    allow_failure: true
    when: manual
    script: "python build_win.py"
    only:
      - develop@platform_sdk/ecmedia
    tags:
      - windows


## -------> deploy
# deploy_br_other_android:
#     stage: deploy
#     script: "cp ../android_*.zip ~/.platform_build/platform_sdk/ecmedia_layer_libs/android/v2.3.x/"
#     only:
#       - vp8_test@platform_sdk/ecmedia
#       - develop@platform_sdk/ecmedia
#     tags:
#       - mac_osx
#     when: manual
#     variables:
#       GIT_STRATEGY: none
    

# deploy_br_other_ios:
#     stage: deploy
#     script: "cp ../ios_*.zip ~/.platform_build/platform_sdk/ecmedia_layer_libs/ios/v2.3.x/"
#     only:
#       - vp8_test@platform_sdk/ecmedia
#       - develop@platform_sdk/ecmedia
#     tags:
#       - mac_osx
#     when: manual
#     variables:
#       GIT_STRATEGY: none
    

# deploy_br_other_win:
#     stage: deploy
#     script: "scp -i private.key ../windows_*.zip seanlee@192.168.178.218:~/.platform_build/platform_sdk/ecmedia_layer_libs/windows/v2.3.x/"
#     only:
#       - vp8_test@platform_sdk/ecmedia
#       - develop@platform_sdk/ecmedia
#     tags:
#       - windows
#     when: manual
#     variables:
#       GIT_STRATEGY: none
